name: sample_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  quiver: ^3.2.1
  get: ^4.6.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_lints: ^2.0.0
  json_to_model: ^3.2.4
  http: ^0.13.5
  file_picker: ^4.0.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  json_annotation: ^4.0.1


flutter:
  uses-material-design: true

